
use_frameworks!

target 'ProatomicSubclasses_Example' do
  pod 'ProatomicSubclasses', :path => '../'

  target 'ProatomicSubclasses_Tests' do
    inherit! :search_paths

#pod 'FBSnapshotTestCase'
  end
end
